### ISSUE TITLE
[Feature] Add cross-references for dependencies

### ISSUE THREAD

**Issue by cosimameyer** [jumpingrivers/diffify#12]
Following my previous [suggestion](https://github.com/jumpingrivers/diffify/issues/11), having cross-references that allow the user to directly jump to the dependencies would be fantastic. 

As a user, I would love to have the cross-references here:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/7782895/227885843-f53376be-f8ce-4515-bcc7-7af89c6cad39.png">

Clicking, for instance, on `future` would then lead me to the (newest; if not stated otherwise) version of the library. This way, I can also access major changes (and licenses, if #11 is implemented) here.

Thanks again for all the fantastic work that went into diffify!

**Comment by timbrock** [comment]
Thanks for the suggestions @cosimameyer! I thinking cross-linking to other packages is a great idea. I'm not sure whether we'll be able to make the link more specific (i.e. to a specific pair of versions) because the versioning can get quite complex and depend on things like python version and (IIRC) operating system.

**Comment by cosimameyer** [comment]
Thanks so much, I understand the hassle linking correct versions may cause. Having "just" the cross-links would be already more than amazing! 🙂

**Comment by timbrock** [comment]
We've implemented this now so thanks again for the suggestion! See our [latest blog post](https://www.jumpingrivers.com/blog/diffify-anniversary-update-r-python/) for  details.

**Comment by cosimameyer** [comment]
Thank you! 🎉
