### ISSUE TITLE
Alert users if package does not have a previous version

### ISSUE THREAD

**Issue by bms63** [jumpingrivers/diffify#3]
I did admiral, a package I work on, and we just released to CRAN in February.  Be cool to see a flag that says no previous versions available.  Maybe I missed it just doing this on my phone

**Comment by timbrock** [comment]
Hi @bms63! Just to understand motivation, are you thinking it's confusing having the latest and earliest dropdowns be the same version and then having an empty diff?

**Comment by bms63** [comment]
Yeah...just something that says this is the only released version to CRAN- nothing to compare.  Maybe an edge-case!  We are about to release another admiral version to CRAN so this becomes moot...but something I thought about when I put in admiral.

**Comment by timbrock** [comment]
We've just added an "Empty package" option to the _Earlier version_ dropdown menu so that any _Later version_ can be compared against "nothing" and you'll see all dependencies and etc for the selected _Later version_, even if there is only one package version. Do you think this negates this issue?

https://diffify.com/R/ggplot2/empty/3.3.6
https://diffify.com/R/admiral/empty/0.6.3

**Comment by bms63** [comment]
Sounds goods to me.  

The wording "Empty Package" seems strange, but I can't come up with anything else.  

Amazing tool by the way!

**Comment by timbrock** [comment]
> The wording "Empty Package" seems strange, but I can't come up with anything else.

If you think of anything else, do let us know.

> Amazing tool by the way!

Thank you!
